language: java
jdk:
 - oraclejdk8

addons:
  sonarcloud:
    organization: "rfaguiar-github" # "sonarcloud_organization_key"  the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
script:
# - mvn clean install -Pprod
  # other script steps might be done before running the actual analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Pprod sonar:sonar

deploy:
  provider: heroku
  api-key:
   secure: $HEROKU_API_KEY
  app: brewer-springmvc-app1
