language: java
script:
 - mvn clean install -Pprod
 - mvn sonar:sonar -Dsonar.organization=rfaguiar-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=
jdk:
 - oraclejdk8
deploy:
  provider: heroku
  api-key:
   secure: $HEROKU_API_KEY
  app: brewer-springmvc-app1

addons:
  sonarcloud:
    organization: "rfaguiar-github" # "sonarcloud_organization_key"  the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar